import type { Artisan, Product, LanguageOption } from './types';

export const languages: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
];

export const translations: Record<string, { title: string; description: string }> = {
  en: {
    title: 'Handcrafted Kalamkari Cotton Shoulder Bag',
    description:
      'A beautifully hand-painted Kalamkari shoulder bag crafted from pure cotton by skilled artisans of Andhra Pradesh. Each piece tells a story through traditional motifs and natural dyes, making it a unique addition to your collection.',
  },
  hi: {
    title: 'हस्तनिर्मित कलमकारी कपास शोल्डर बैग',
    description:
      'आंध्र प्रदेश के कुशल कारीगरों द्वारा शुद्ध कपास से बनाया गया सुंदर हाथ से चित्रित कलमकारी शोल्डर बैग। प्रत्येक टुकड़ा पारंपरिक रूपांकनों और प्राकृतिक रंगों के माध्यम से एक कहानी कहता है।',
  },
  te: {
    title: 'చేతితో తయారు చేసిన కలంకారి కాటన్ బ్యాగ్',
    description:
      'ఆంధ్రప్రదేశ్ నైపుణ్యం గల కళాకారులచే స్వచ్ఛమైన కాటన్‌తో చేతితో చిత్రించిన కలంకారి బ్యాగ్. ప్రతి ముక్క సాంప్రదాయ చిత్రాల ద్వారా కథను చెబుతుంది.',
  },
  ta: {
    title: 'கையால் செய்யப்பட்ட கலம்காரி பருத்தி பை',
    description:
      'ஆந்திராவின் திறமையான கைவினைஞர்களால் தூய பருத்தியால் கையால் வரையப்பட்ட கலம்காரி பை. ஒவ்வொன்றும் பாரம்பரிய வடிவங்கள் மற்றும் இயற்கை வண்ணங்கள் மூலம் கதையைக் கூறுகிறது.',
  },
  kn: {
    title: 'ಕೈಯಿಂದ ತಯಾರಿಸಿದ ಕಲಂಕಾರಿ ಹತ್ತಿ ಬ್ಯಾಗ್',
    description:
      'ಆಂಧ್ರಪ್ರದೇಶದ ನುರಿತ ಕುಶಲಕರ್ತರಿಂದ ಶುದ್ಧ ಹತ್ತಿಯಿಂದ ಕೈಯಿಂದ ಚಿತ್ರಿಸಲಾದ ಸುಂದರ ಕಲಂಕಾರಿ ಬ್ಯಾಗ್. ಪ್ರತಿ ತುಣುಕು ಸಾಂಪ್ರದಾಯಿಕ ವಿನ್ಯಾಸಗಳ ಮೂಲಕ ಕಥೆಯನ್ನು ಹೇಳುತ್ತದೆ.',
  },
  bn: {
    title: 'হস্তনির্মিত কলমকারি কাপড় ব্যাগ',
    description:
      'অন্ধ্রপ্রদেশের দক্ষ কারিগরদের দ্বারা বিশুদ্ধ সুতি কাপড় থেকে তৈরি হাতে আঁকা কলমকারি ব্যাগ। প্রতিটি টুকরো ঐতিহ্যবাহী নকশা এবং প্রাকৃতিক রং এর মাধ্যমে একটি গল্প বলে।',
  },
  mr: {
    title: 'हस्तनिर्मित कलमकारी कापड बॅग',
    description:
      'आंध्र प्रदेशातील कुशल कारागीरांद्वारे शुद्ध कापडापासून हाताने रंगवलेला कलमकारी बॅग. प्रत्येक तुकडा पारंपरिक नमुन्यांद्वारे एक कथा सांगतो.',
  },
  ml: {
    title: 'കൈകൊണ്ട് നിർമ്മിച്ച കലംകാരി കോട്ടൺ ബാഗ്',
    description:
      'ആന്ധ്രയിലെ നിപുണരായ കരകൗശലക്കാരാൽ ശുദ്ധ കോട്ടണിൽ കൈകൊണ്ട് വരച്ച കലംകാരി ബാഗ്. ഓരോ കഷണും പാരമ്പര്യ രൂപങ്ങളിലൂടെ ഒരു കഥ പറയുന്നു.',
  },
};

export const artisans: Artisan[] = [
  {
    id: 'a1',
    name: 'Lakshmi Devi',
    village: 'Srikalahasti',
    state: 'Andhra Pradesh',
    craft: 'Kalamkari',
    specialization: 'Hand-painted Textiles',
    yearsExperience: 22,
    story:
      'I learned Kalamkari from my mother, who learned from hers. For three generations, our family has painted stories onto cotton using natural dyes made from indigo, madder, and myrobalan. Every piece I create carries the breath of my ancestors.',
    image:
      'https://images.pexels.com/photos/11538902/pexels-photo-11538902.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    rating: 4.9,
    followers: 1240,
    productsCount: 12,
    verified: true,
    languages: ['Telugu', 'Hindi', 'English'],
  },
  {
    id: 'a2',
    name: 'Ramesh Kumar',
    village: 'Etikoppaka',
    state: 'Telangana',
    craft: 'Woodcraft',
    specialization: 'Hand-carved Wooden Toys',
    yearsExperience: 18,
    story:
      'I carve toys from soft Ankudu wood, colored with natural vegetable dyes. My village has been making these toys for over 400 years. I want the world to know our craft and the love we put into every piece.',
    image:
      'https://images.pexels.com/photos/17536627/pexels-photo-17536627.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    rating: 4.8,
    followers: 890,
    productsCount: 9,
    verified: true,
    languages: ['Telugu', 'Hindi'],
  },
  {
    id: 'a3',
    name: 'Meena Bai',
    village: 'Chanderi',
    state: 'Madhya Pradesh',
    craft: 'Handloom Weaving',
    specialization: 'Chanderi Silk Sarees',
    yearsExperience: 30,
    story:
      'Weaving Chanderi sarees is not just my profession, it is my meditation. Each saree takes 7-10 days on the handloom, with motifs inspired by the forts and palaces of my homeland. I have trained 15 young women in this art.',
    image:
      'https://images.pexels.com/photos/11565514/pexels-photo-11565514.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    rating: 5.0,
    followers: 2100,
    productsCount: 15,
    verified: true,
    languages: ['Hindi', 'English'],
  },
  {
    id: 'a4',
    name: 'Savitri Devi',
    village: 'Bankura',
    state: 'West Bengal',
    craft: 'Terracotta',
    specialization: 'Terracotta Pottery & Sculpture',
    yearsExperience: 25,
    story:
      'The clay of Bankura speaks through my hands. I shape terracotta horses, elephants, and pots using techniques passed down for generations. Each piece is fired in traditional kilns using rice husk.',
    image:
      'https://images.pexels.com/photos/18626462/pexels-photo-18626462.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    rating: 4.7,
    followers: 650,
    productsCount: 8,
    verified: true,
    languages: ['Bengali', 'Hindi'],
  },
  {
    id: 'a5',
    name: 'Arjun Singh',
    village: 'Moradabad',
    state: 'Uttar Pradesh',
    craft: 'Brass Craft',
    specialization: 'Hand-engraved Brassware',
    yearsExperience: 20,
    story:
      'Moradabad is the brass city of India. I engrave decorative plates, lamps, and figurines using techniques my grandfather taught me. Each piece is hammered, engraved, and polished by hand.',
    image:
      'https://images.pexels.com/photos/17293003/pexels-photo-17293003.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    rating: 4.8,
    followers: 1100,
    productsCount: 11,
    verified: true,
    languages: ['Hindi', 'English'],
  },
  {
    id: 'a6',
    name: 'Priya Nair',
    village: 'Aranmula',
    state: 'Kerala',
    craft: 'Bamboo Craft',
    specialization: 'Bamboo Baskets & Home Decor',
    yearsExperience: 15,
    story:
      'I weave bamboo into baskets, lampshades, and home decor. Bamboo is sustainable and beautiful. I work with a women\'s collective that empowers rural women through craft.',
    image:
      'https://images.pexels.com/photos/19823777/pexels-photo-19823777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    rating: 4.6,
    followers: 540,
    productsCount: 7,
    verified: true,
    languages: ['Malayalam', 'English'],
  },
];

const img = {
  kalamkariBag: 'https://images.pexels.com/photos/21326994/pexels-photo-21326994.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  kalamkariBag2: 'https://images.pexels.com/photos/36933384/pexels-photo-36933384.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  saree1: 'https://images.pexels.com/photos/10317106/pexels-photo-10317106.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  saree2: 'https://images.pexels.com/photos/38890438/pexels-photo-38890438.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  saree3: 'https://images.pexels.com/photos/10317127/pexels-photo-10317127.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  pottery1: 'https://images.pexels.com/photos/34545851/pexels-photo-34545851.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  pottery2: 'https://images.pexels.com/photos/11042854/pexels-photo-11042854.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  pottery3: 'https://images.pexels.com/photos/3145866/pexels-photo-3145866.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  wood1: 'https://images.pexels.com/photos/6443886/pexels-photo-6443886.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  wood2: 'https://images.pexels.com/photos/30996822/pexels-photo-30996822.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  wood3: 'https://images.pexels.com/photos/30996818/pexels-photo-30996818.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  jewelry1: 'https://images.pexels.com/photos/33737455/pexels-photo-33737455.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  jewelry2: 'https://images.pexels.com/photos/9704263/pexels-photo-9704263.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  jewelry3: 'https://images.pexels.com/photos/32828107/pexels-photo-32828107.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  leather1: 'https://images.pexels.com/photos/37060871/pexels-photo-37060871.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  leather2: 'https://images.pexels.com/photos/21326994/pexels-photo-21326994.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  painting1: 'https://images.pexels.com/photos/33952938/pexels-photo-33952938.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  painting2: 'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  painting3: 'https://images.pexels.com/photos/36785041/pexels-photo-36785041.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  brass1: 'https://images.pexels.com/photos/15755947/pexels-photo-15755947.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  brass2: 'https://images.pexels.com/photos/20083403/pexels-photo-20083403.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  brass3: 'https://images.pexels.com/photos/26792961/pexels-photo-26792961.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bamboo1: 'https://images.pexels.com/photos/35264910/pexels-photo-35264910.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bamboo2: 'https://images.pexels.com/photos/35105858/pexels-photo-35105858.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bamboo3: 'https://images.pexels.com/photos/31047258/pexels-photo-31047258.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  embroidery1: 'https://images.pexels.com/photos/19026107/pexels-photo-19026107.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  embroidery2: 'https://images.pexels.com/photos/29475576/pexels-photo-29475576.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  embroidery3: 'https://images.pexels.com/photos/34887544/pexels-photo-34887544.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
};

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Handcrafted Kalamkari Cotton Shoulder Bag',
    artisanId: 'a1',
    artisanName: 'Lakshmi Devi',
    artisanState: 'Andhra Pradesh',
    category: 'Handbags',
    craft: 'Kalamkari',
    material: 'Cotton',
    technique: 'Hand-painted',
    color: 'Blue',
    region: 'Andhra Pradesh',
    price: 1650,
    originalPrice: 2100,
    rating: 4.9,
    reviews: 127,
    image: img.kalamkariBag,
    images: [img.kalamkariBag, img.kalamkariBag2, img.embroidery3],
    description:
      'A beautifully hand-painted Kalamkari shoulder bag crafted from pure cotton by skilled artisans of Andhra Pradesh. Each piece tells a story through traditional motifs and natural dyes, making it a unique addition to your collection.',
    tags: ['Handmade', 'Kalamkari', 'Cotton', 'Artisan', 'Hand-painted', 'Traditional Craft', 'Eco-friendly'],
    dimensions: '30 x 25 x 8 cm',
    stock: 5,
    estimatedDelivery: '5-7 days',
    trending: true,
    featured: true,
  },
  {
    id: 'p2',
    name: 'Royal Banarasi Silk Saree with Gold Zari',
    artisanId: 'a3',
    artisanName: 'Meena Bai',
    artisanState: 'Madhya Pradesh',
    category: 'Sarees',
    craft: 'Handloom Weaving',
    material: 'Silk',
    technique: 'Handwoven',
    color: 'Blue & Gold',
    region: 'Madhya Pradesh',
    price: 8500,
    originalPrice: 11000,
    rating: 5.0,
    reviews: 89,
    image: img.saree2,
    images: [img.saree2, img.saree1, img.saree3],
    description:
      'A luxurious handwoven silk saree with intricate gold zari work. This masterpiece took 10 days to create on a traditional handloom, featuring motifs inspired by ancient temple architecture.',
    tags: ['Handmade', 'Silk', 'Handloom', 'Zari', 'Wedding', 'Luxury', 'Traditional'],
    dimensions: '5.5m x 1.2m',
    stock: 3,
    estimatedDelivery: '7-10 days',
    trending: true,
    featured: true,
  },
  {
    id: 'p3',
    name: 'Bankura Terracotta Horse Sculpture',
    artisanId: 'a4',
    artisanName: 'Savitri Devi',
    artisanState: 'West Bengal',
    category: 'Home Decor',
    craft: 'Terracotta',
    material: 'Terracotta Clay',
    technique: 'Hand-molded & Fired',
    color: 'Terracotta Red',
    region: 'West Bengal',
    price: 1200,
    rating: 4.7,
    reviews: 54,
    image: img.pottery1,
    images: [img.pottery1, img.pottery2, img.pottery3],
    description:
      'The iconic Bankura horse, a symbol of Bengali folk art. Hand-molded from local clay and fired in traditional kilns. Each piece is unique and carries centuries of cultural significance.',
    tags: ['Handmade', 'Terracotta', 'Folk Art', 'Home Decor', 'Bengal', 'Eco-friendly'],
    dimensions: '25 x 30 x 8 cm',
    stock: 8,
    estimatedDelivery: '5-7 days',
    featured: true,
  },
  {
    id: 'p4',
    name: 'Hand-carved Wooden Temple Elephant',
    artisanId: 'a2',
    artisanName: 'Ramesh Kumar',
    artisanState: 'Telangana',
    category: 'Wooden Crafts',
    craft: 'Woodcraft',
    material: 'Ankudu Wood',
    technique: 'Hand-carved',
    color: 'Natural Brown',
    region: 'Telangana',
    price: 2400,
    originalPrice: 3000,
    rating: 4.8,
    reviews: 42,
    image: img.wood1,
    images: [img.wood1, img.wood2, img.wood3],
    description:
      'A meticulously hand-carved wooden elephant from Etikoppaka. Made from soft Ankudu wood and finished with natural vegetable dyes. A perfect blend of tradition and artistry.',
    tags: ['Handmade', 'Woodcraft', 'Hand-carved', 'Decor', 'Traditional', 'Natural Dye'],
    dimensions: '20 x 15 x 10 cm',
    stock: 6,
    estimatedDelivery: '5-7 days',
    trending: true,
  },
  {
    id: 'p5',
    name: 'Handmade Silver-tone Stone Earrings',
    artisanId: 'a6',
    artisanName: 'Priya Nair',
    artisanState: 'Kerala',
    category: 'Jewelry',
    craft: 'Wire-wrapping',
    material: 'Stone & Wire',
    technique: 'Wire-wrapped',
    color: 'Blue',
    region: 'Kerala',
    price: 850,
    rating: 4.6,
    reviews: 73,
    image: img.jewelry3,
    images: [img.jewelry3, img.jewelry1, img.jewelry2],
    description:
      'Elegant handmade earrings featuring natural blue stones wrapped in silver-tone wire. Each pair is unique, crafted with precision by artisans who blend contemporary design with traditional techniques.',
    tags: ['Handmade', 'Jewelry', 'Earrings', 'Wire-wrapped', 'Stone', 'Gift'],
    dimensions: '3 x 2 cm',
    stock: 12,
    estimatedDelivery: '3-5 days',
  },
  {
    id: 'p6',
    name: 'Engraved Brass Decorative Diya Lamp',
    artisanId: 'a5',
    artisanName: 'Arjun Singh',
    artisanState: 'Uttar Pradesh',
    category: 'Home Decor',
    craft: 'Brass Craft',
    material: 'Brass',
    technique: 'Hand-engraved',
    color: 'Gold',
    region: 'Uttar Pradesh',
    price: 1450,
    originalPrice: 1800,
    rating: 4.8,
    reviews: 61,
    image: img.brass1,
    images: [img.brass1, img.brass2, img.brass3],
    description:
      'A hand-engraved brass diya lamp from Moradabad, the brass city of India. Features intricate floral patterns and a warm golden glow. Perfect for festive decor and gifting.',
    tags: ['Handmade', 'Brass', 'Engraved', 'Diya', 'Festive', 'Home Decor', 'Gift'],
    dimensions: '12 x 12 x 8 cm',
    stock: 10,
    estimatedDelivery: '5-7 days',
    trending: true,
  },
  {
    id: 'p7',
    name: 'Bamboo Wall Decor Basket Set',
    artisanId: 'a6',
    artisanName: 'Priya Nair',
    artisanState: 'Kerala',
    category: 'Home Decor',
    craft: 'Bamboo Craft',
    material: 'Bamboo',
    technique: 'Hand-woven',
    color: 'Natural',
    region: 'Kerala',
    price: 950,
    rating: 4.6,
    reviews: 38,
    image: img.bamboo1,
    images: [img.bamboo1, img.bamboo2, img.bamboo3],
    description:
      'A set of hand-woven bamboo baskets from Kerala, perfect for wall decor or storage. Made by a women\'s collective promoting sustainable craft and rural empowerment.',
    tags: ['Handmade', 'Bamboo', 'Woven', 'Eco-friendly', 'Home Decor', 'Sustainable'],
    dimensions: 'Set of 3 (20, 25, 30 cm)',
    stock: 15,
    estimatedDelivery: '5-7 days',
  },
  {
    id: 'p8',
    name: 'Hand-painted Madhubani Wall Art',
    artisanId: 'a4',
    artisanName: 'Savitri Devi',
    artisanState: 'West Bengal',
    category: 'Paintings',
    craft: 'Madhubani Painting',
    material: 'Canvas',
    technique: 'Hand-painted',
    color: 'Multicolor',
    region: 'West Bengal',
    price: 3200,
    originalPrice: 4000,
    rating: 4.9,
    reviews: 29,
    image: img.painting2,
    images: [img.painting2, img.painting1, img.painting3],
    description:
      'A vibrant Madhubani painting on canvas, depicting traditional motifs of nature and mythology. Each stroke is painted by hand using natural pigments, carrying the soul of Indian folk art.',
    tags: ['Handmade', 'Madhubani', 'Painting', 'Wall Art', 'Folk Art', 'Canvas'],
    dimensions: '60 x 40 cm',
    stock: 4,
    estimatedDelivery: '7-10 days',
    featured: true,
  },
  {
    id: 'p9',
    name: 'Embroidered Cotton Cushion Cover Pair',
    artisanId: 'a1',
    artisanName: 'Lakshmi Devi',
    artisanState: 'Andhra Pradesh',
    category: 'Home Decor',
    craft: 'Kalamkari',
    material: 'Cotton',
    technique: 'Hand-painted',
    color: 'Red & Blue',
    region: 'Andhra Pradesh',
    price: 750,
    rating: 4.5,
    reviews: 47,
    image: img.embroidery3,
    images: [img.embroidery3, img.embroidery1, img.embroidery2],
    description:
      'A pair of hand-painted Kalamkari cushion covers in vibrant red and blue. Made from pure cotton with natural dyes. Adds a touch of traditional elegance to any living space.',
    tags: ['Handmade', 'Kalamkari', 'Cotton', 'Cushion', 'Home Decor', 'Eco-friendly'],
    dimensions: '40 x 40 cm (pair)',
    stock: 20,
    estimatedDelivery: '3-5 days',
  },
  {
    id: 'p10',
    name: 'Handwoven Kanchipuram Silk Saree',
    artisanId: 'a3',
    artisanName: 'Meena Bai',
    artisanState: 'Madhya Pradesh',
    category: 'Sarees',
    craft: 'Handloom Weaving',
    material: 'Silk',
    technique: 'Handwoven',
    color: 'Red & Green',
    region: 'Madhya Pradesh',
    price: 12000,
    originalPrice: 15000,
    rating: 5.0,
    reviews: 34,
    image: img.saree1,
    images: [img.saree1, img.saree3, img.saree2],
    description:
      'A magnificent Kanchipuram-style silk saree with rich traditional motifs and contrast border. Handwoven over 12 days, this saree is a heirloom piece meant to be treasured for generations.',
    tags: ['Handmade', 'Silk', 'Handloom', 'Kanchipuram', 'Wedding', 'Luxury', 'Heirloom'],
    dimensions: '5.5m x 1.2m',
    stock: 2,
    estimatedDelivery: '10-14 days',
    trending: true,
  },
  {
    id: 'p11',
    name: 'Hand-carved Wooden Ganesha Statue',
    artisanId: 'a2',
    artisanName: 'Ramesh Kumar',
    artisanState: 'Telangana',
    category: 'Wooden Crafts',
    craft: 'Woodcraft',
    material: 'Ankudu Wood',
    technique: 'Hand-carved',
    color: 'Natural Brown',
    region: 'Telangana',
    price: 3800,
    rating: 4.9,
    reviews: 56,
    image: img.wood2,
    images: [img.wood2, img.wood3, img.wood1],
    description:
      'A divine hand-carved wooden Ganesha statue, crafted with devotion by master artisans. Each detail is meticulously carved to capture the serenity and grace of Lord Ganesha.',
    tags: ['Handmade', 'Woodcraft', 'Ganesha', 'Religious', 'Decor', 'Hand-carved'],
    dimensions: '25 x 20 x 12 cm',
    stock: 5,
    estimatedDelivery: '7-10 days',
  },
  {
    id: 'p12',
    name: 'Brass Wind Chime with Bells',
    artisanId: 'a5',
    artisanName: 'Arjun Singh',
    artisanState: 'Uttar Pradesh',
    category: 'Home Decor',
    craft: 'Brass Craft',
    material: 'Brass',
    technique: 'Hand-cast',
    color: 'Gold',
    region: 'Uttar Pradesh',
    price: 1100,
    rating: 4.5,
    reviews: 33,
    image: img.brass2,
    images: [img.brass2, img.brass3, img.brass1],
    description:
      'A melodious brass wind chime with hand-cast bells from Araku Valley. Each bell produces a unique, soothing tone. Perfect for balconies, gardens, or doorways.',
    tags: ['Handmade', 'Brass', 'Wind Chime', 'Decor', 'Bells', 'Gift'],
    dimensions: '45 cm length',
    stock: 14,
    estimatedDelivery: '3-5 days',
  },
];

export const categories = [
  { name: 'Handbags', icon: 'ShoppingBag', count: 24, color: 'saffron' },
  { name: 'Sarees', icon: 'Shirt', count: 18, color: 'magenta' },
  { name: 'Home Decor', icon: 'Home', count: 32, color: 'turquoise' },
  { name: 'Jewelry', icon: 'Gem', count: 21, color: 'gold' },
  { name: 'Wooden Crafts', icon: 'TreePine', count: 15, color: 'coral' },
  { name: 'Paintings', icon: 'Palette', count: 12, color: 'royal' },
  { name: 'Pottery', icon: 'Coffee', count: 19, color: 'teal' },
  { name: 'Brass Crafts', icon: 'Lightbulb', count: 9, color: 'indigo' },
];

export const sellerOrders = [
  { id: 'ORD-2401', product: 'Handcrafted Kalamkari Cotton Shoulder Bag', productImage: img.kalamkariBag, customer: 'Ananya Sharma', amount: 1650, date: '2026-09-04', status: 'new' as const },
  { id: 'ORD-2402', product: 'Embroidered Cotton Cushion Cover Pair', productImage: img.embroidery3, customer: 'Raj Patel', amount: 750, date: '2026-09-04', status: 'processing' as const },
  { id: 'ORD-2403', product: 'Handcrafted Kalamkari Cotton Shoulder Bag', productImage: img.kalamkariBag, customer: 'Sneha Reddy', amount: 1650, date: '2026-09-03', status: 'shipped' as const },
  { id: 'ORD-2404', product: 'Embroidered Cotton Cushion Cover Pair', productImage: img.embroidery3, customer: 'Vikram Singh', amount: 750, date: '2026-09-02', status: 'delivered' as const },
  { id: 'ORD-2405', product: 'Handcrafted Kalamkari Cotton Shoulder Bag', productImage: img.kalamkariBag, customer: 'Pooja Iyer', amount: 1650, date: '2026-09-01', status: 'delivered' as const },
  { id: 'ORD-2406', product: 'Embroidered Cotton Cushion Cover Pair', productImage: img.embroidery3, customer: 'Arjun Nair', amount: 750, date: '2026-08-31', status: 'delivered' as const },
];

export const sellerNotifications = [
  { id: 'n1', type: 'order' as const, title: 'New Order Received', message: 'Ananya Sharma ordered Kalamkari Cotton Bag', time: '5 min ago', read: false, role: 'seller' as const },
  { id: 'n2', type: 'views' as const, title: 'Product Getting More Views', message: 'Your Kalamkari Bag is trending! 34% more views today', time: '1 hour ago', read: false, role: 'seller' as const },
  { id: 'n3', type: 'price' as const, title: 'Price Recommendation Updated', message: 'AI suggests a new competitive price for your cushion covers', time: '3 hours ago', read: false, role: 'seller' as const },
  { id: 'n4', type: 'trend' as const, title: 'Market Trend Detected', message: 'Kalamkari handbags are trending this week', time: '5 hours ago', read: true, role: 'seller' as const },
  { id: 'n5', type: 'product' as const, title: 'Product Approved', message: 'Your Kalamkari Bag is now live and visible to buyers', time: '1 day ago', read: true, role: 'seller' as const },
];

export const buyerNotifications = [
  { id: 'bn1', type: 'delivery' as const, title: 'Order Shipped', message: 'Your Kalamkari Bag is on the way!', time: '2 hours ago', read: false, role: 'buyer' as const },
  { id: 'bn2', type: 'collection' as const, title: 'New Artisan Collection', message: 'Meena Bai just added new Chanderi sarees', time: '5 hours ago', read: false, role: 'buyer' as const },
  { id: 'bn3', type: 'delivery' as const, title: 'Out for Delivery', message: 'Your terracotta horse is out for delivery today', time: '1 day ago', read: true, role: 'buyer' as const },
];

export const revenueData = [
  { month: 'Mar', revenue: 8500, orders: 6 },
  { month: 'Apr', revenue: 12000, orders: 9 },
  { month: 'May', revenue: 9500, orders: 7 },
  { month: 'Jun', revenue: 15500, orders: 11 },
  { month: 'Jul', revenue: 18200, orders: 13 },
  { month: 'Aug', revenue: 22000, orders: 15 },
  { month: 'Sep', revenue: 24850, orders: 18 },
];

export const viewsData = [
  { day: 'Mon', views: 145 },
  { day: 'Tue', views: 178 },
  { day: 'Wed', views: 210 },
  { day: 'Thu', views: 189 },
  { day: 'Fri', views: 245 },
  { day: 'Sat', views: 312 },
  { day: 'Sun', views: 268 },
];

export const topProducts = [
  { name: 'Kalamkari Bag', views: 420, sales: 8, revenue: 13200 },
  { name: 'Cushion Covers', views: 280, sales: 6, revenue: 4500 },
  { name: 'Saree', views: 195, sales: 2, revenue: 17000 },
  { name: 'Wall Art', views: 150, sales: 1, revenue: 3200 },
];

export const trendingCrafts = [
  { name: 'Kalamkari', trend: 'up', change: '+34%', demand: 'High' },
  { name: 'Handloom', trend: 'up', change: '+22%', demand: 'High' },
  { name: 'Terracotta', trend: 'up', change: '+15%', demand: 'Medium' },
  { name: 'Bamboo Crafts', trend: 'up', change: '+18%', demand: 'Medium' },
  { name: 'Handmade Jewelry', trend: 'up', change: '+12%', demand: 'High' },
  { name: 'Brassware', trend: 'down', change: '-5%', demand: 'Low' },
];

export const priceTrendData = [
  { month: 'Mar', price: 1400 },
  { month: 'Apr', price: 1450 },
  { month: 'May', price: 1500 },
  { month: 'Jun', price: 1550 },
  { month: 'Jul', price: 1580 },
  { month: 'Aug', price: 1620 },
  { month: 'Sep', price: 1650 },
];

export const comparableProducts = [1450, 1500, 1550, 1600, 1650, 1700, 1750, 1800, 1500, 1550, 1600, 1650];

export const searchSuggestions = [
  'Kalamkari bags',
  'Handwoven sarees',
  'Handmade jewelry',
  'Gifts under ₹1000',
  'Products from Telangana',
  'Eco-friendly crafts',
  'Terracotta pottery',
  'Wooden handicrafts',
];

export const artisanStories = [
  {
    artisanId: 'a1',
    title: 'Three Generations of Kalamkari',
    excerpt: 'Lakshmi Devi preserves a 300-year-old painting tradition in Srikalahasti...',
    image: 'https://images.pexels.com/photos/11538902/pexels-photo-11538902.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    artisanId: 'a3',
    title: 'The Loom That Tells Stories',
    excerpt: 'Meena Bai weaves Chanderi sarees that carry the motifs of ancient forts...',
    image: 'https://images.pexels.com/photos/11565514/pexels-photo-11565514.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    artisanId: 'a4',
    title: 'Clay That Speaks',
    excerpt: 'Savitri Devi shapes Bankura horses from the earth of her village...',
    image: 'https://images.pexels.com/photos/18626462/pexels-photo-18626462.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
];
